name: Deploy Static Website

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code                                 #Gets your source code
        uses: actions/checkout@v4

      - name: Setup Pages                                  #Sets up GitHub Pages env
        uses: actions/configure-pages@v4

      - name: Upload Static Files                          #Packages files to deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  
          
      - name: Deploy to GitHub Pages                      #deploys the site
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Check if DISCORD_WEBHOOK secret is available
        run: echo ${{ secrets.DISCORD_WEBHOOK }}
        
      - name: Notify Discord
        if: always()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "✅ Website successfully deployed from obsirium/website!"
